FROM almalinux:latest

RUN yum install -y git

#RUN groupadd -g 1000 luser && \
#    useradd -m -u 1000 -g 1000 -s /bin/bash luser && \
#    echo "luser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
#
#SHELL ["/bin/bash", "-c"]
#
## Set the default user
#USER luser